// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "StudyBuddy",
    platforms: [
        .iOS("27.0")
    ],
    products: [
        .iOSApplication(
            name: "StudyBuddy",
            targets: ["AppModule"],
            bundleIdentifier: "studybuddy.swiftpm.StudyBuddy",
            teamIdentifier: "ZT7BLN8CZ5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone,
                .mac
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    dependencies: [
        .package(url: "https://github.com/supabase/supabase-swift.git", "2.0.0"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Supabase", package: "supabase-swift")
            ],
            path: ".",
            resources: [
                .copy(".env"),
                .copy("lofi_study.wav"),
                .copy("rain_nature.wav"),
                .copy("cafe_ambient.wav")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)